/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tilavuus;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class tilavuus extends javax.swing.JFrame {

    /**
     * Creates new form tilavuus
     */
    public tilavuus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblKanta = new javax.swing.JLabel();
        jtxtKanta = new javax.swing.JTextField();
        jlblKorkeus = new javax.swing.JLabel();
        jtxtKorkeus = new javax.swing.JTextField();
        jlblSyvyys = new javax.swing.JLabel();
        jtxtSyvyys = new javax.swing.JTextField();
        jbtnLaske = new javax.swing.JButton();
        jtxtTilavuus = new javax.swing.JTextField();
        jlblTilavuus = new javax.swing.JLabel();
        jlblKantavirhe = new javax.swing.JLabel();
        jlblKorkeusvirhe = new javax.swing.JLabel();
        jlblSyvyysvirhe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblKanta.setText("Kanta:");

        jlblKorkeus.setText("Korkeus:");

        jtxtKorkeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKorkeusActionPerformed(evt);
            }
        });

        jlblSyvyys.setText("Syvyys:");

        jbtnLaske.setText("Laske tilavuus");
        jbtnLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLaskeActionPerformed(evt);
            }
        });

        jlblTilavuus.setText("Tilavuus:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTilavuus)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnLaske)
                            .addComponent(jlblSyvyys)
                            .addComponent(jlblKorkeus)
                            .addComponent(jlblKanta)
                            .addComponent(jtxtKanta)
                            .addComponent(jtxtKorkeus)
                            .addComponent(jtxtSyvyys)
                            .addComponent(jtxtTilavuus, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblKantavirhe, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jlblKorkeusvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSyvyysvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jlblKanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblKantavirhe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblKorkeus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKorkeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblKorkeusvirhe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblSyvyys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSyvyys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSyvyysvirhe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnLaske)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblTilavuus)
                .addGap(9, 9, 9)
                .addComponent(jtxtTilavuus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtKorkeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKorkeusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKorkeusActionPerformed

    private void jbtnLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLaskeActionPerformed
        // TODO add your handling code here:
        float kanta, korkeus, syvyys, tilavuus;
        
        try {
            kanta = Float.parseFloat(jtxtKanta.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        if (kanta<=0) {
            jlblKantavirhe.setForeground(Color.red);
            jlblKantavirhe.setText("Kanta täytyy olla suurempi tai yhtäsuuri kuin nolla.");
            return;
        } else {
            jlblKantavirhe.setText("");
        }
                 
        try {
            korkeus = Float.parseFloat(jtxtKorkeus.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        if (korkeus<=0) {
            jlblKorkeusvirhe.setForeground(Color.red);
            jlblKorkeusvirhe.setText("Korkeus täytyy olla suurempi tai yhtäsuuri kuin nolla.");
            return;
        } else {
            jlblKorkeusvirhe.setText("");
        }
                     
        try {
            syvyys = Float.parseFloat(jtxtSyvyys.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        if (syvyys<=0) {
            jlblSyvyysvirhe.setForeground(Color.red);
            jlblSyvyysvirhe.setText("Syvyys täytyy olla suurempi tai yhtäsuuri kuin nolla.");
            return;
        } else {
            jlblSyvyysvirhe.setText("");
        }
        
        // Lasketaan tilavuus
        tilavuus = kanta*korkeus*syvyys;
          
        jtxtTilavuus.setText(String.format("%.2f",tilavuus));
        
    }//GEN-LAST:event_jbtnLaskeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tilavuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tilavuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tilavuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tilavuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tilavuus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLaske;
    private javax.swing.JLabel jlblKanta;
    private javax.swing.JLabel jlblKantavirhe;
    private javax.swing.JLabel jlblKorkeus;
    private javax.swing.JLabel jlblKorkeusvirhe;
    private javax.swing.JLabel jlblSyvyys;
    private javax.swing.JLabel jlblSyvyysvirhe;
    private javax.swing.JLabel jlblTilavuus;
    private javax.swing.JTextField jtxtKanta;
    private javax.swing.JTextField jtxtKorkeus;
    private javax.swing.JTextField jtxtSyvyys;
    private javax.swing.JTextField jtxtTilavuus;
    // End of variables declaration//GEN-END:variables
}
